server:
  port: 8084

moex:
  server:
    url: http://localhost:8080

bot:
  name: "@getMarketDataBot"
  token: "6261330794:AAH-_jMBk0r4CgnEqRIuKKsJ7Us-uv64AvY"

spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true
  sql:
    init:
      mode: always
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/stocks
    username: postgres
    password: postgres




